language: cpp
matrix:
  include:
  - os: linux
    sudo: false
    compiler: gcc
    env: PLATFORM=linux64
  - os: osx
    compiler: clang
    env: PLATFORM=osx
script: make dist
notifications:
  email:
    recipients:
    - bengchet@cytron.com.my
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: j5kWKpgvSMzF4+0rq+4MiVrxQMz2MybG5kq86LWP7deDqWnT53eMUgenHgnZMDjDE8nIZ0zZB0r3MELdyMJKEtmVYlgmMXIaH1T4CnfwIIVWoLeWLplGDh96y9Ebj1DpB9jB4hasBKG3z6pAEgChmCMX0Wx1fiMhrsr+qAtQj8ohR4AG9OFUNGPKbeI1ncWD3aZq1T2V+/OImAtmVMD/gcilKtT/XaQv9eCOKtsSefeaEFz8QEuS5q2c/eCBVSUaY0FLknk+bLT5aEWC+2BmrB6jFqKF3rkIZ8/siEfTERzMuZnhQ22/3gCddvAYbXF/gI2mnjqgMxhzGtj2MABiflhARZkx8/I36alTe/6nosKgOe3RMnjGp0N8uDKH5ipiel5j0Dc9BhdcMkC2N+aTaS5Fg7TDPCOoX73CS2Ryf2x6TOam47/zzJQm1Wdjufw1LQ93H27L6Y3cddsApYrh07qr0lPi1DbU/JWThpBuuTlN73Dy8fDIdRPcBxjc+b8VJs8GwfzvzOPptKQBgp2AD9GRznZM/05UBOppDL00uRvS4q26H8Ks8pyAT6ziJt6eLIHn+oakqR3U8wxkCwEWnk931FZ7/ax88gEQ5mYBcq2zNNeDI/Hxix8tHDxhmmgxf0biTT1ApakFeLlfBzPTQ7AlOYb0T6tM0rYtTuF4znQ=
  file: nuvodude-$TRAVIS_TAG-$PLATFORM.tar.gz
  on:
    repo: bengchet/nuvodude
    tags: true
